var tigger = {character: 'Tigger'}
var pooh = {character: 'Winnie the Pooh'}
var piglet = {character: 'Piglet'}
var bees = {character: 'bees'}
var owl = {character: 'Owl'}
var robin = {character: 'Christopher Robin'}
var rabbit = {character: 'Rabbit'}
var gopher = {character: 'Gopher'}
var kanga = {character: 'Kanga'}
var eeyore = {character: 'Eeyore'}
var heffalumps = {character: 'Heffalumps'}

tigger.north = pooh;
pooh.north = robin;
pooh.east = bees;
pooh.south = tigger;
pooh.west = piglet;
piglet.north = owl;
piglet.east = pooh;
bees.west =  pooh;
bees.north = rabbit;
owl.east = robin;
owl.south = piglet;
robin.north = kanga;
robin.east = rabbit;
robin.south = pooh;
robin.west = owl;
rabbit.east = gopher;
rabbit.south = bees;
rabbit.west = robin;
gopher.west = rabbit;
kanga.north = eeyore;
kanga.south = robin;
eeyore.south = kanga;
eeyore.east =  heffalumps;
heffalumps.west = eeyore;
